language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t xkmd/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true xkmd/react-test npm test
after_success:
  - docker build -t xkmd/multi-client ./client
  - docker build -t xkmd/multi-nginx ./nginx
  - docker build -t xkmd/multi-server ./server
  - docker build -t xkmd/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push xkmd/multi-client
  - docker push xkmd/multi-nginx
  - docker push xkmd/multi-server
  - docker push xkmd/multi-worker
